### ISSUE TITLE
[Feature Request] Support alb-ingress-controller v2.x.x

### ISSUE THREAD

**Issue by peimanja** [iplabs/terraform-kubernetes-alb-ingress-controller#11]
alb-ingress-controller v2 has released.

**Comment by mogul** [comment]
I've implemented this in https://github.com/iplabs/terraform-kubernetes-alb-ingress-controller/pull/13

**Comment by headcr4sh** [comment]
Thanks for the work, @mogul!

Support for the new AWS Ingress Controller that I am looking forward to and it's definitely on my wishlist.

I think it doesn't make sense though, to create a new Github repository (`terraform-kubernetes-aws-ingress-controller`) to reflect the changes in the upstream software package. I will therefore *not* merge your pull request into this repository, because I feel that a new repository would be the better fit.

I am also not quite sure if Helm is the way to go here and I am right now thinking about using the new `kubernetes-alpha` provider plugin (which will eventually be merged back into the stable kubernetes provider plugin). I am not quite sure about the pros and cons at this point and will have to think a bit before making a quick decision.

**Comment by mercuriete** [comment]
@mogul 
I am trying your repo and you forgot to add
```alb_controller_depends_on = something ```

In the snippet example inside the README.md

so your PR doesn't work using the example which is bad.

BTW, I can't open issues on this repo: https://github.com/GSA/terraform-kubernetes-aws-load-balancer-controller
so, please open the possibility to report issues because I don't want to pollute this issue.

Thank you very much @mogul
